apiVersion: v1
kind: Pod
metadata:
  name: product-api
  labels:
    name: product-api
spec:
  containers:
  - name: product-api
    image: product-api:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
